language: node_js
node_js:
- '16.20.0'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # MATTERMOST_HOOK_URL
  - secure: D+J9k0P+/zAyaMZFx9pn+rS1kk1mvbW7LhqzshI6ctT+UC1EToB/h5HrtCR4hBLKz795H6vRrJwXD7JwTNvXiZFDS+n1qqTYywKzynTQWXIe9J584DbuFLo9H4mNPjLxFSqMXIEU5scpdfxyTB+IzRyVxzh77yF+JGsAGd4KOzduHMPMFJpmw+VykGpcalJtg1GigBbr837CNJmaWT4UN+lTocr5q5kXgC9WBTA5RGrc/1bKFySwUitUD6/5LK1Tgv7sPuQTACZKUx73lcNHXSOi2msfZaOoUcN2Y8gZQdvhBG7vUh6DHZe67i4MYg37vitnbOLlOASEyD+qpT8qUzdFnJbDNoDbYMJ9UZfOYYETT3XQBKhlCUabz17LuPHqIQ1t+HEYldmggwwhypD293NuPtCb4j++t9RvGtVThyQwHYnYSuRfvKuAOk7oXKE/54wHacXWWz302CwihKH++z5lRYS1TT5YX6SPciFjtVT6qLEr6oYqCZVdprx9XztRFtUT2s3Cjwegs84g+vycQtj1x6WSK3YvdLIPgPDSG8YqqFjrg0ks+J8HTaKem6n1upay9Nsnr6U2PPYNMddafn04+VXtQ8UPmTWKDNOMvORpoCzsnoQIXYG5EUN7yWarsViFQZ8r6QTlYqzy1x/UFwSKvFPJT/4eRkSadGhSm0o=
  # REGISTRY_TOKEN slug=payfit editor=cozy space=cozy_ccc
  - secure: ak2KCxMS8WznA8WUigTw2xAuwSY1Dmfzz6HhUBxaQJJri31dZHI3D9mPcOEtSeoNWgi1Mhz1wEQ/Mda7uJ0F+WhuMUtd9TOH3mNHe1CdnhQkDUQ6H/NZsxZYtZ5P2oZ64r6igB9x6pcK+98Fs/1z8UXsSndo6ffDNJNBo0Zx4Ujc0nzB4UTk8B9DF93UARtx208O7Ovxw5r3TZNNIUF11ZnHKs633txN8J8teZhPjdEfWGvA1On4XjXo1KbQQZ2A/JhltQAgr0Zyi8MMcazKY/4Xwr1iq0S5+tsVCnRYWUEuqsrT96kF+QEBNHyVYx3RmDJchk7B0D+2fDHfGjf2mc+VlL0N/W5G9JWZeNOXQMcElfH9YlsDcHRTC9zdndVNm7yajWMM5MGLGp5lHLE1QYnf2VMhKD/uinHkvSIzdPPxtIBqiocIZwtT9c1UPpTNvknS/m6wPtp2fcUGK56izS4Ldl7fnHiQlhQBIKSCrpw5fZMlGqteHYD3EdKGwB6S1P4d2o9kqJjBQpVit1/uNhH7OEnR3x61s9j7Q+XW6zNl8prKUAugFuxe69s1dAxI+kaZ3c6AQLBkTCfFaWjkd1WEx/kg2+65Yl/Cxwaqc6xF4JET0Og5+O/K8dhqEXbn2y7Yv8ck5mRSWW5WWL9RXk9O+3kQY4E0vkyPlMXUV7c=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --space cozy_ccc
  on:
    branch:
    - master
    - main
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost --space cozy_ccc
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D
