language: node_js
node_js:
- '16.20.2'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # MATTERMOST_HOOK_URL
  - secure: D+J9k0P+/zAyaMZFx9pn+rS1kk1mvbW7LhqzshI6ctT+UC1EToB/h5HrtCR4hBLKz795H6vRrJwXD7JwTNvXiZFDS+n1qqTYywKzynTQWXIe9J584DbuFLo9H4mNPjLxFSqMXIEU5scpdfxyTB+IzRyVxzh77yF+JGsAGd4KOzduHMPMFJpmw+VykGpcalJtg1GigBbr837CNJmaWT4UN+lTocr5q5kXgC9WBTA5RGrc/1bKFySwUitUD6/5LK1Tgv7sPuQTACZKUx73lcNHXSOi2msfZaOoUcN2Y8gZQdvhBG7vUh6DHZe67i4MYg37vitnbOLlOASEyD+qpT8qUzdFnJbDNoDbYMJ9UZfOYYETT3XQBKhlCUabz17LuPHqIQ1t+HEYldmggwwhypD293NuPtCb4j++t9RvGtVThyQwHYnYSuRfvKuAOk7oXKE/54wHacXWWz302CwihKH++z5lRYS1TT5YX6SPciFjtVT6qLEr6oYqCZVdprx9XztRFtUT2s3Cjwegs84g+vycQtj1x6WSK3YvdLIPgPDSG8YqqFjrg0ks+J8HTaKem6n1upay9Nsnr6U2PPYNMddafn04+VXtQ8UPmTWKDNOMvORpoCzsnoQIXYG5EUN7yWarsViFQZ8r6QTlYqzy1x/UFwSKvFPJT/4eRkSadGhSm0o=
  # REGISTRY_TOKEN(editor=cozy, app=payfit)
  - secure: cHaVViHbKx9Wk7I/D0AH/vmc0hPyB/Ysnya3gekZHPuA9wKV+yXIKB9fqZxUOT6NZfPNBLBJqpPGHtFMlea+6fNKTOuB7k4+XwBMTPCaEJUazi/yAvg81GCljUV2PC+ZLwoLl898q8OG7UNL2tFmBBv6BWpQi0vy/oHA2/N3g71Y2ukvxUkWfTbNbzUmqYzky0Nap+YSYIrkwM/I58e/DPz1uYAkuGm1vzpEfu565xSCCpnMk2fbKuUe8AbUqU5vTYv1HQdatl7DmaFFkmPnxUUKSnz7MnEI+6VAJZtgT1K+5abDJW8KqzjwBvqJcIOX6CrPiBZEh+cn+SnZh78WxqG3W5Za7/c4tXHaK2E2BSaxJdYOD/zqOhknIGbRUi83hmNwx6t1aP5bPXtd7EsGFGVSuC1qcIXdsLXMOpgq3Bp1WGLmVuPFtSFuWanJuOhymPl62oPm4v2CVyIuy1Fhg8NHOIeABbkjCisBQpbpdnC/DiV4CQfbG4D6pXPrJQFLdXU9Dk8l4Xx+/KSNXihPY2MTIMkvgJdgw9DN3jlRahQtJig4K4c+HHA59F8W3x3zkCS9tRJUEu7dm9SHUVR+5+UkU8sjFjnuu4HaKsgli2OY9BwWisvVkTACuONZVgwDLD3TWhhhQbwsWW28G2/2TR9ADChevQbnQLQYHtExagc=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch:
    - master
    - main
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D
