language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
after_success:
  - test $TRAVIS_BRANCH = "master" && yarn run deploy:travis -- --branch=build
